### ISSUE TITLE
Some small ui issues

### ISSUE THREAD

**Issue by luongvo** [HossamOnsy/NimbleTask#3]
Please cross check with our test requirements if are there sth missing or incorrect:
- No **app title** and **menu** on right in titlebar, all components in titlebar should in in **white**
- Vertical pager indicators: unselected indicator should be **non-filled**, **no zoom-in** animation when switching pager, all indicators should be **showed to fill maximize of pager's height** (instead of just show for 9 items)
- Pager: survey title should be **bigger**
- Colors seem did not match (**title bar color**)

**Comment by HossamOnsy** [comment]
Done , confirm to close the issue :D

**Comment by luongvo** [comment]
Your new implementation doesn't work, this bring a **bad result**. Did you test the app before pushing the code? Also please try to split pull request (PR) to be smaller PRs and focus to the main task of that PR, instead of 1 commit 1 PR for with everything.

![2019_06_28_16_45_48](https://user-images.githubusercontent.com/16315358/60333953-91c8b380-99c4-11e9-91de-7fc560394bbe.gif)

**Comment by luongvo** [comment]
This one still did not resolved:
- Vertical pager indicators: **unselected indicator should be non-filled, no zoom-in animation should be applied when switching pager**, ~all indicators should be showed to fill maximize of pager's height (instead of just show for 9 items)~
